### ISSUE TITLE
Add jupyter-datascience-notebooks template

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-community/templates#2]
This seems to be a good first template to add. It's been discussed in https://github.com/orgs/devcontainers-community/discussions/1#discussioncomment-5351589

Here's a tentative todo thingy:
- [x] Reach out to the original maintainer @nathancarter
- [x] Get their permission to move/improve/do stuff
- [x] Add the actual code content into this repo
- [ ] OPTIONAL: Deprecate and/or document the change in the original location? unsure of how to go about this. I wasn't involved with devcontainers-related stuff until Nov 2022 which was _after_ the deprecation of https://github.com/microsoft/vscode-dev-containers i think... @eitsupi will probably need to assist me and/or do this

@nathancarter Are you interested in being added as a collaborator, or would you prefer to make it more of a "transferring the torch" kinda thing?

**Comment by eitsupi** [comment]
Thanks for taking this up. I will make this as an example case.

**Comment by eitsupi** [comment]
I created a PR #5 to adding the Template.
I would appreciate your opinion.

There is no agreement on what information should be included in the document at this time, so there are only minimal notes.
Ideally, we should put the names of the maintainers, as in https://github.com/microsoft/vscode-dev-containers.

**Comment by jcbhmr** [comment]
> I would appreciate your opinion.

💕 I genuinely  really appreciate the cooperative/collaborative spirit/attitude!

**Comment by nathancarter** [comment]
@jcbhmr I think I'm content for it to be a torch-passing.  If you look at the file, there's really nothing to it anyway--it just does one trivial setup step to be able to run Microsoft's Debian setup script in the container Jupyter provides, and that's it.  (Okay, plus some settings and test files.)
