### ISSUE TITLE
Fix Linter failuers

### ISSUE THREAD

**Issue by eitsupi** [devcontainers-community/templates#37]
A large number of Linter errors are currently occurring and must be corrected.

**Comment by jcbhmr** [comment]
I just want to say a massive _thank you_ ♥️ for a) putting up with my bad merging habit (which I hope to improve) and b) fixing them.

0 lint errors! 🎉 Nice! https://github.com/devcontainers-community/templates/actions/runs/5232371418/jobs/9447049331
