### ISSUE TITLE
Set up linting workflow

### ISSUE THREAD

**Issue by eitsupi** [devcontainers-community/templates#4]
I recommend MegaLinter.
https://megalinter.io/latest/

I have often used Super-Linter (https://github.com/github/super-linter, like https://github.com/rocker-org/devcontainer-templates/blob/9f90b59bf0ed97dde1ffc048e0ae98a5734dc5b5/.github/workflows/lint.yaml), but I prefer to set up MegaLinter because it is more flexible in configuration and updated more frequently.

**Comment by jcbhmr** [comment]
Sounds great! I'll defer to you on all this convention/linting/settings stuff as I kinda alluded to in [devcontainers-community#4](https://github.com/orgs/devcontainers-community/discussions/4#discussioncomment-5357278). -- you seem to know what you're doing ❤
